### ISSUE TITLE
The public directory is not served at server root.

### ISSUE THREAD

**Issue by ram-you** [antfu/vitesse-nuxt3#13]
The **public** directory is not served at server root on build.
Failed to load resource: the server responded with a status of 404 () for images nuxt.png and vite.png
https://vitesse-nuxt3.netlify.app/
![Capture d’écran_2021-12-03_08-36-28](https://user-images.githubusercontent.com/3125972/144563997-f343fe74-bb25-4c93-aa0f-68566dc9346b.png)

**Comment by ijpatricio** [comment]
I can confirm the same behaviour on my end.

You don't even need to put on production.
Steps:
- Clone the repo
- npm install
- npm run dev # works OK!
- npm run build
- npm start # does NOT work

It seems to me this is related to paths on the `.output/public/...`.
It's my first time at both, Vitesse and Nuxt.
Let me know if I can assist with more executions/ tests on my side @antfu @Atinux

**Comment by pauloguerraf** [comment]
temporary workaround until fixed is to use "@/public/" instead 

i.e.   
`  <img  src="/nuxt.png" /> becomes   <img  src="@/public/nuxt.png" />
`

**Comment by ijpatricio** [comment]
Thank @pauloguerraf and @antfu .
Just tried the latest version, and everything is working 👍 

This project is *insane*!! So, so good!!
