### ISSUE TITLE
Runtime compiler

### ISSUE THREAD

**Issue by ijpatricio** [antfu/vitesse-nuxt3#14]
Hello @antfu

Again, this is a great template! I've been playing with it for my personal website, but now I want to give it a go with something more advanced.

Now I'm trying to have the runtime compiler both in server and client. I do this because I use Laravel to get pages/partials already with translated content and permission-based content ready from the backend.
I'm trying to use https://github.com/mattelen/vue3-runtime-template (it works with webpack)

Is it too hard to have the runtime compiler with `vitesse-nuxt3`?

Right now, it works out of the box, server-side.

![image](https://user-images.githubusercontent.com/26031459/146443216-4176595e-829c-4090-b286-4f83472c33ee.png)

```
    <div>
      Foo bar
      <v-runtime-template :template="template"></v-runtime-template>
    </div>

  </section>
</template>

<script>
import VRuntimeTemplate from "vue3-runtime-template"

export default {
  components: { VRuntimeTemplate },
  data: () => ({
    template: `foo var bas <counter></counter>`
  }),
}
</script>
```

So, in SSR, all good!

But then, in the client, there's no runtime compiler

![image](https://user-images.githubusercontent.com/26031459/146443385-66d2d200-5a08-4fb6-ab10-82c3008e444d.png)

I try to fix it by aliasing ´vue´ with for the `vue.esm.bundler`, but then I break the server.

Is this an easy fix? Or can you give me some light onto solving this?

I'm invested in doing it, just give me some pointers, I will find a fix and make a PR.

**Comment by ijpatricio** [comment]
Ok, got it!

Adding to `nuxt.js.config` :
```
    hooks: {
      'vite:extendConfig': (config, { isClient, isServer }) => {
        if (isClient) {
          config.resolve.alias.vue = 'vue/dist/vue.esm-bundler'
        }
      },
    },
```

solved it!

Pheeew that was hard for me to figure out! Feels good!

Would you like some PR for this??

I think it's a real boost in development speed: not having to put all i18n or permissions in JS, but instead rendering from backend partials.

Is it possible to somehow import and register a component, after the first mount...
For sake of example... an app mounts, all good... 5 seconds lates, I click a button, that fetches HTML from backend, and renders it in a modal...
This HTML has components that are not registered in Vue, and the .js file is available in a URL...

Is this possible, or is it a dream??

**Comment by antfu** [comment]
I guess what you want to achieve might be possible but requires more effort to research. Giving it might not be a common need, I'd feel it's out-of-scope of this starter template. Closing for now, good luck!

**Comment by ijpatricio** [comment]
Ok, thanks for your time!

A few days ago we interacted on a tweet, you were facing a very difficult phase. Hope it got better, or as soon as possible.
I can't imagine how I could help, let me know if there is a way!
Sending much love, hang in there ❤️
