### ISSUE TITLE
dark mode does not apply for initial load of the page.

### ISSUE THREAD

**Issue by portlek** [antfu/vitesse-nuxt3#24]
there is an issue about dark mode when you open the [page](https://vitesse-nuxt3.netlify.app/) it looks like in dark mode in the backend, i say this because when you click the dark mode button it does not anything but, the second click it goes to dark mode. i guess there is an issue where is in the backend of dark mode things. it does not update the front-end for initial load of the page. tried in incognito mode. because it caches the state of the dark mode.

**Comment by Atinux** [comment]
I think switching to https://color-mode.nuxtjs.org would be best 😊
