### ISSUE TITLE
cannot read file   /.nuxt/tsconfig.json

### ISSUE THREAD

**Issue by JanHuyBE** [antfu/vitesse-nuxt3#41]
![screen 2022-05-04 104424](https://user-images.githubusercontent.com/81109502/166649184-5d03a9dd-9391-42cd-852c-c9dead98aef3.jpg)

The tsconfig.json gives an error on the first bracket in the my-nuxt3app/tsconfig.json file.

Cannot read file '... my-nuxt3-app/.nuxt/tsconfig.json'.  ts

**Comment by danielroe** [comment]
You need to run `nuxt prepare` (or `nuxt dev`) to generate the types.

**Comment by JanHuyBE** [comment]
![screen 2022-05-04 113205](https://user-images.githubusercontent.com/81109502/166656419-4c16443b-2be0-4918-96f7-0a968f4ed78c.jpg)

**Comment by danielroe** [comment]
You run it with npm or yarn. Typically as a script in your package.json.

**Comment by JanHuyBE** [comment]
![screen 2022-05-04 113857](https://user-images.githubusercontent.com/81109502/166657856-97887abd-75a1-481f-866d-659579ca5691.jpg)

**Comment by danielroe** [comment]
Run `npm run dev`.

**Comment by JanHuyBE** [comment]
![screen 2022-05-04 114245](https://user-images.githubusercontent.com/81109502/166658500-fc2a0e6e-c9d4-42f1-9ba0-84058cfc8cbc.jpg)

**Comment by danielroe** [comment]
That's an error that npm is giving you. It sounds pretty straightforward. Definitely investigate it. Maybe you are running the command in the wrong directory?

**Comment by JanHuyBE** [comment]
![screen 2022-05-04 114814](https://user-images.githubusercontent.com/81109502/166659428-de8e4793-0a52-44a0-accc-27c94f5ae10d.jpg)

I get the same error if I start a clean Nuxt 3.0.0-rc2 installation

**Comment by portlek** [comment]
use pnpm instead of npm, it's working for me.

**Comment by JanHuyBE** [comment]
![screen 2022-05-05 185827](https://user-images.githubusercontent.com/81109502/166974743-109603ea-e6b9-4b98-a6ad-dfda3aee1770.jpg)
I tried in different ways with npm npx and pnpm, no positive result.
The closest result ends on this.

**Comment by xSuffix** [comment]
> As soon as I want to add a module to Nuxt3RC2, I get errors. I also tried to install other modules.

This happened for me aswell, using Windows 10. Disabling `viteNode` in nuxt.config.ts helped.

**nuxt.config.ts**
`import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  modules: [
    '@vueuse/nuxt',
    '@unocss/nuxt',
    '@pinia/nuxt',
    '@nuxtjs/color-mode',
  ],
  experimental: {
    reactivityTransform: true,
    // viteNode: true,
  },
  unocss: {
    preflight: true,
  },
  colorMode: {
    classSuffix: '',
  },
})
`

Here's what I found on viteNode:

- https://github.com/nuxt/framework/issues/3598
- https://v3.nuxtjs.org/api/configuration/nuxt.config#vitenode

**Comment by JanHuyBE** [comment]
xSuffix, Jan Fröhlich,

Thank you, it worked,    und es machte mich Fröhlich

1./
Before running the 'npm install' I added in the 'nuxt.config.ts'

        export default defineNuxtConfig({
             experimental: {
                 reactivityTransform: true,
                 viteNode: false,
                }

Hereafter I could run 'npm i -D @unocss/nuxt' and adding in 'nuxt.config.ts' the module to it.
I did not have an error when I run 'npm run dev -- -o'      ----OK

2./
For installing a fresh 'vitesse' i did the following:
npx degit antfu/vitesse-nuxt3 my-nuxt3-app
cd my-nuxt3-app

then I changed the 'nuxt.config.ts' with 
          export default defineNuxtConfig({
               experimental: {
                   reactivityTransform: true,
                   viteNode: false,
                  }

then 'pnpm i'    -----OK

It worked also.
THANK YOU
