### ISSUE TITLE
'nuxt dev' 500s on a fresh install with ssr: false

### ISSUE THREAD

**Issue by daniil4udo** [antfu/vitesse-nuxt3#43]
**Environment**

- Operating System: macOS Monterey
- Node Version: v16.13.1
- Nuxt Version: 3.0.0-rc.3
- Package Manager: pnpm@7
- Builder: vite
- User Config: ssr

**Logs**

`useState@http://localhost:3000/_nuxt/node_modules/.pnpm/nuxt@3.0.0-rc.3/node_modules/nuxt/dist/app/composables/state.mjs:7:26
@http://localhost:3000/_nuxt/node_modules/.pnpm/@nuxtjs+color-mode@3.0.3/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.mjs:7:29
fn@http://localhost:3000/_nuxt/node_modules/.pnpm/nuxt@3.0.0-rc.3/node_modules/nuxt/dist/app/nuxt.mjs:106:27
callWithNuxt@http://localhost:3000/_nuxt/node_modules/.pnpm/nuxt@3.0.0-rc.3/node_modules/nuxt/dist/app/nuxt.mjs:111:12
applyPlugin@http://localhost:3000/_nuxt/node_modules/.pnpm/nuxt@3.0.0-rc.3/node_modules/nuxt/dist/app/nuxt.mjs:68:29
applyPlugins@http://localhost:3000/_nuxt/node_modules/.pnpm/nuxt@3.0.0-rc.3/node_modules/nuxt/dist/app/nuxt.mjs:77:11
async*initApp@http://localhost:3000/_nuxt/entry.mjs:44:13
@http://localhost:3000/_nuxt/entry.mjs:60:3
`

Seems lie a problem with `@nuxtjs/color-mode` package [(related)](https://github.com/nuxt-community/color-mode-module/issues/143)

**Result**

<img width="1629" alt="image" src="https://user-images.githubusercontent.com/34333374/170815333-5a8335f9-542c-4e37-8e27-26d31163c539.png">

**Comment by antfu** [comment]
Please report to upstream.
