### ISSUE TITLE
Use `.md` file in route

### ISSUE THREAD

**Issue by chris-zhu** [antfu/vitesse-nuxt3#48]
Can share a example about `vite-plugin-md`? Hope Like [vitesse `about.md`](https://github.com/antfu/vitesse/blob/main/src/pages/about.md)
I refer to [unocss interactive markdown module](https://github.com/unocss/unocss/blob/main/interactive/modules/markdown.ts), but meet some errors

**Comment by antfu** [comment]
Maybe Nuxt Content would be better fit?

**Comment by chris-zhu** [comment]
Thanks, and i will try to use it in other way.
