### ISSUE TITLE
Bulid and deploy in docker failed with exit code 134.

### ISSUE THREAD

**Issue by jarvis000000** [antfu/vitesse-nuxt3#50]
#### error:
![Snipaste_2022-07-15_10-42-46](https://user-images.githubusercontent.com/59681983/179136681-5a7eff6f-937a-4e0a-a464-eb7a0b2617da.png)

#### Dockerfile:
```Dockerfile
FROM node:16.15.1
COPY . .

RUN npm config set registry https://registry.npm.taobao.org --global
RUN npm install -g pnpm
RUN pnpm install
RUN pnpm run build
RUN npm install -g pm2

EXPOSE 3000

CMD [ "pm2-runtime", "start", ".output/server/index.mjs" ]
```
####  .dockerignore:
```.dockerignore
node_modules
.output
.nuxt
```

#### pnpm build & pnpm start are running properly in the local environment

**Comment by jarvis000000** [comment]
I replaced "nuxt": "^3.0.0-rc.4" with "nuxt": "^3.0.0-rc.5" in the package.json.
It can be build successfully in docker.But there is a new error:
![docker-error](https://user-images.githubusercontent.com/59681983/179143476-885a59d3-4db5-4815-98bf-44027f410e3e.png)
![image](https://user-images.githubusercontent.com/59681983/179143508-1f607f65-4837-4d4d-b60f-c68121275e2f.png)

**Comment by cinob** [comment]
upgrade @pinia/nuxt
