### ISSUE TITLE
"jsx" error in Counter.vue

### ISSUE THREAD

**Issue by joaquin-leimeter** [antfu/vitesse-nuxt3#51]
### Describe the bug

The error `Cannot use JSX unless the '--jsx' flag is provided. ts(17004)` is present in `src/components/Conter.vue` file.

Extensions: Eslint, Prettier, Typescript Vue Plugin (Volar), Vue Language Features, WindiCSS Intellisense.

A possible fix is to add `"jsx": "preserve"` to `compilerOptions` in `tsconfig.json`.

### Reproduction

clone the template, run pnpm i, go to src/components/Conter.vue to see the errror

### System Info

```Shell
System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 155.01 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 101.0.1
    Safari: 15.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Did you run `nuxi prepare` or `nuxi dev` once? We are extending `.nuxt/tsconfig.json`, which is auto-generated.

**Comment by joaquin-leimeter** [comment]
I didn't about that 😢, thanks for the quick answer. I could make a PR adding the command in the readme file, under the "Try it now!" section, is that ok?

**Comment by antfu** [comment]
Or we could add `postinstall` script with `nuxi prepare`. /cc @danielroe what do you think about the best way to avoid this confusion?

**Comment by danielroe** [comment]
I think a postinstall command is a nice idea 🔥
