### ISSUE TITLE
 Netlify online preview error

### ISSUE THREAD

**Issue by cinob** [antfu/vitesse-nuxt3#52]
### Describe the bug

![image](https://user-images.githubusercontent.com/30230686/179892682-74238e83-db3c-44ab-905e-b76126ef0522.png)
![image](https://user-images.githubusercontent.com/30230686/179892743-2618de1a-af75-40a1-838a-014374e87e38.png)

### Reproduction

https://vitesse-nuxt3.netlify.app/

### System Info

```Shell
~
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ZiadJ** [comment]
And this is what I'm getting on FIrefox 103:
![image](https://user-images.githubusercontent.com/1817207/182287845-0031b6c4-b25b-4d95-bc9b-ba6e95542a11.png)

**Comment by pi0** [comment]
This is a known issue with Nuxt 3 RC.5 and RC.6 and this issue is probably related. Please try https://github.com/nuxt/framework/issues/6204#issuecomment-1201398080 as workaround.
