### ISSUE TITLE
PWA Support 

### ISSUE THREAD

**Issue by rashidpathiyil** [antfu/vitesse-nuxt3#53]
### Clear and concise description of the problem

PWA Support is missing feature of this template which is very important one.

### Suggested solution

Maybe it helps 
https://github.com/kevinmarrec/nuxt-pwa-module

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
We are waiting for Nuxt's PWA to support Nuxt 3
