### ISSUE TITLE
What parameter cl means?

### ISSUE THREAD

**Issue by snoooopy-ch** [antfu/vitesse-nuxt3#54]
### Clear and concise description of the problem

Hi 

`<nuxt-layout cl>`

I see it doesn't work without cl parameter.
Would you let me know what cl means?

Best,

### Suggested solution

no

### Validations

- [ ] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [ ] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
... it's a typo 😅 PR welcome to remove it

**Comment by therealokoro** [comment]
hehehe 😂, for a minute there I thought that was some unocss utility class for `console.log`
