### ISSUE TITLE
Error when update nuxt to 3.0.0-rc.8

### ISSUE THREAD

**Issue by billymaulana** [antfu/vitesse-nuxt3#56]
### Describe the bug

im update nuxt to 3.0.0-rc.8.
and then when pnpm build.
<img width="713" alt="image" src="https://user-images.githubusercontent.com/13347455/186719890-f6724549-0bc6-473a-a7a4-7030879af89a.png">

### Reproduction

upgrade nuxt to 3.0.0-rc.8.

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 716.69 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 104.1.42.97
    Chrome: 104.0.5112.101
    Firefox Developer Edition: 105.0
    Safari: 15.6.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
a6d3353e1de4a6650422efc867eb24a7dd025345 update your lock with `pnpm up`
