### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by weskhaled** [antfu/vitesse-nuxt3#6]
{
errorType: "Runtime.ImportModuleError",
errorMessage: "Error: Cannot find module 'node:http'
Require stack:
- /var/task/.netlify/functions-internal/server/server.js
- /var/task/server.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js",
trace: [
"Runtime.ImportModuleError: Error: Cannot find module 'node:http'",
"Require stack:",
"- /var/task/.netlify/functions-internal/server/server.js",
"- /var/task/server.js",
"- /var/runtime/UserFunction.js",
"- /var/runtime/index.js",
"    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
"    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
"    at Object.<anonymous> (/var/runtime/index.js:43:30)",
"    at Module._compile (internal/modules/cjs/loader.js:999:30)",
"    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
"    at Module.load (internal/modules/cjs/loader.js:863:32)",
"    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
"    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
"    at internal/main/run_main_module.js:17:47"
]
}

**Comment by antfu** [comment]
Use the latest Node.js
