### ISSUE TITLE
Nuxi 3.0.0-rc.13   版本 NuxtLink 切换页面路由失效

### ISSUE THREAD

**Issue by cestrongly** [antfu/vitesse-nuxt3#65]
### Describe the bug

bug 重现分支
https://gitee.com/cestr/bsc-geega-web/tree/1.0.0-stage-1%2Fdevelop/
正常分支 "nuxt": "^3.0.0-rc.11",
https://gitee.com/cestr/bsc-geega-web/tree/1.0.0-stage-1%2Fmain/

### Reproduction

https://gitee.com/cestr/bsc-geega-web/tree/1.0.0-stage-1%2Fdevelop/

### System Info

```Shell
OS:Windows 10 22H2
Edge: 107
Node: 16.18.0
npm: 8.19.2 
pnpm: 7.14.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Seems to work fine for me now with 3.0
