### ISSUE TITLE
Update @antfu/eslint-config to make defined globals from nuxt works

### ISSUE THREAD

**Issue by lerayj** [antfu/vitesse-nuxt3#77]
### Clear and concise description of the problem

I guess it's more a @antfu/eslint-config issue, but since it's Nuxt 3 related and i'm not sure it make sense I will post it here.

<img width="538" alt="Capture d’écran 2023-02-10 à 17 32 16" src="https://user-images.githubusercontent.com/5832419/218145009-79713999-7e6c-4afe-883e-378bff64c1e2.png">

As show on the screenshot `defineEventHandler` isn't found, even if auto imported is a "standard".

### Suggested solution

I tried to extends with differents nuxt3 specific eslint. Unfortunally adding them on top of your config break eslint.
I guess it would be better to just make it works on your config - then no other eslint dep is needed.  

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I don't think I have `no-undef` configured in my eslint config. Please provide a reproduction.
