### ISSUE TITLE
Nuxt ^3.4.0 版本，VueUse useColorMode 方法切换主题模式失效

### ISSUE THREAD

**Issue by pinky-pig** [antfu/vitesse-nuxt3#84]
### Describe the bug

今天升级 nuxt 3.4 后，发现使用的 `useColorMode` 失效，不能修改 `<html class='light'>` 。  
来到 `vitesse-nuxt3` 仓库看 commit log 也已经更新了 3.4，下载code，run后，也是失效的。  
在线的 <https://vitesse-nuxt3.netlify.app/> 也没有效果。

![bug](https://user-images.githubusercontent.com/42307398/231341991-b0585824-a137-4172-bb65-a48405942be6.gif)

### Reproduction

https://vitesse-nuxt3.netlify.app/

### System Info

```Shell
OS:Windows 10 22H2
Node: 18.12.0
npm: 8.19.2 
pnpm: 7.21.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CavinHuang** [comment]
初步排查是useState无效了，3.4的更新文档好像并没有这个api的更新

**Comment by ram-you** [comment]
https://github.com/nuxt/nuxt/issues/20211#issuecomment-1503832655

**Comment by CavinHuang** [comment]
@ram-you 感谢你的回答，experimental.renderJsonPayloads。确实能够解决这个问题。
