### ISSUE TITLE
希望集成 husky 和 windcss

### ISSUE THREAD

**Issue by mei2015** [antfu/vitesse-nuxt3#85]
### Clear and concise description of the problem

希望集成 husky 和 windcss

### Suggested solution

希望集成 husky 和 windcss

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
No.

**Comment by weiyidechicheng** [comment]
有unocss了，你想p吃呢
