### ISSUE TITLE
plus icon flashing/stuck on mobile

### ISSUE THREAD

**Issue by pauloguerraf** [antfu/vitesse-nuxt3#9]
Getting the following issue with the + icon when deploying to Vercel ([https://vitesse-starter.vercel.app](https://vitesse-starter.vercel.app)) and accessing the site on mobile. Sometimes the icon flashes when loading the site for the first time, too. Not sure where this comes from.

https://user-images.githubusercontent.com/1149371/143479207-25560883-8bcd-4865-b4a1-f89ebca0ed02.mp4

**Comment by antfu** [comment]
This seems to be a Chrome bug I think

**Comment by ram-you** [comment]
@pauloguerraf , like @antfu said, it's a chrome bug.
Just replace **transform** with **hover:transform** in Logo.vue component.

**Comment by pauloguerraf** [comment]
Thank you for your help @antfu and @ram-you. Fixed.
